name: 'devcontainer-build-run'
description: 'Action to simplify using VS Code dev containers in GitHub workflows'
author: 'stuartleeks'
branding:
  color: purple
  icon: box
inputs:
  imageName:
    required: true
    description: Image name (including registry)
  imageTag:
    required: false
    description: Image tag (defaults to latest)
  runCmd:
    required: true
    description: Specify the command to run after building the dev container image
  subFolder:
    required: false
    description: Specify a child folder (containing a .devcontainer) instead of using the repository root
    default: 
  checkoutPath:
    required: false
    description: Specify path to checked out folder if not using default (or for testing with nektos/act)
    default: .
  push:
    required: false
    default: filter
    description: Control when images are pushed. Options are never, filter, always. For filter (default), images are pushed if the refFilterForPush and eventFilterForPush conditions are met
  refFilterForPush:
    required: false
    default:
    description: Set the source branches (e.g. refs/heads/main) that are allowed to trigger a push of the dev container image. Leave empty to allow all.
  eventFilterForPush:
    required: false
    default: push
    description: Set the event names (e.g. pull_request, push) that are allowed to trigger a push of the dev container image. Defaults to push. Leave empty for all
  env:
    required: false
    description: Specify environment variables to pass to the docker run command
runs:
  using: 'node12'
  main: 'github-action/dist/index.js'
  post: 'github-action/dist/index.js'
  post-if: 'success()'
