name: 'devcontainer-build-run'
description: 'Action to simplify using VS Code dev containers in GitHub workflows'
author: 'stuartleeks'
inputs:
  imageName:
    required: true
    description: Image name (including registry)
  checkoutPath:
    required: false
    description: Specify path to checked out folder if not using default (or for testing with nektos/act)
    default: .
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
