name: 'devcontainer-build-run'
description: 'Action to simplify using VS Code dev containers in GitHub workflows'
author: 'stuartleeks'
inputs:
  imageName:
    required: true
    description: Image name (including registry)
  runCmd:
    required: true
    description: Specify the command to run after building the dev container image
  subFolder:
    required: false
    description: Specify a child folder (containing a .devcontainer) instead of using the repository root
    default: 
  checkoutPath:
    required: false
    description: Specify path to checked out folder if not using default (or for testing with nektos/act)
    default: .
  env:
    required: false
    description: Specify environment variables to pass to the docker run command
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
  post-if: 'success()'
