---
name: CI (branch)
# This workflow is triggered manually and can be used to test workflow changes on a branch (which aren't picked up by the pr-bot builds)

on:
  workflow_dispatch:
    inputs:
      prNumber:
        description: set to the PR number if testing a branch for a PR (used to derive the image tag)
        default: ''
        type: string
        required: false

jobs:
  build-test-publish:
    name: "Build, test, publish"
    uses: ./.github/workflows/ci_common.yml
    with:
      release: false
      prNumber: ${{ inputs.prNumber }}
    secrets:
      AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}
      MARKETPLACE_TOKEN: ${{ secrets.MARKETPLACE_TOKEN }}
