---
name: CI (main)
# This workflow is triggered on pushes to main and runs tests and performs the release steps

on:
  push:
    branches: [chrmarti/deafening-dingo]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build-test-publish:
    name: "Build, test, publish"
    if: github.ref == 'refs/heads/chrmarti/deafening-dingo'
    uses: ./.github/workflows/ci_common.yml
    with:
      release: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZDO_TOKEN: ${{ secrets.AZDO_TOKEN }}
