---
name: pr_auto
# This workflow is triggered automatically for pull requests and runs tests without credentials
# I.e. doesn't validate image caching, doesn't perform tests in Azure DevOps.

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md
      - 'docs/**'

permissions:
  id-token: write
  contents: write
  packages: write

jobs:
  build-test:
    name: "Build, test, publish"
    uses: ./.github/workflows/ci_common.yml
    with:
      prNumber: ${{ github.event.pull_request.number }}
      release: false
      runFullTests: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
