name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:

      - name: Determine checkout-path
        run: |
          if [[ $GITHUB_ACTOR == "nektos/act" ]]; then checkout_path="devcontainer-build-run"; else checkout_path="."; fi
          echo "::set-output name=checkout-path::$checkout_path"
        id: checkout-path

      # Perform checkout to specific path when we're running in nektos/act - see https://github.com/nektos/act/commit/f29b1f2523f5162fa42554870269160a4fb51419
      - name: Checkout (nektos/act)
        uses: actions/checkout@v2
        if: ${{ github.actor == 'nektos/act' }}
        with:
           path: devcontainer-build-run
      - name: Checkout (GitHub)
        uses: actions/checkout@v2
        if: ${{ github.actor != 'nektos/act' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: dev container!
        uses: ./
        with:
          checkoutPath: ${{ steps.checkout-path.outputs.checkout-path }}
          imageName: ghcr.io/stuartleeks/test-devcontainer

      # - name: fail
      #   run: |
      #     echo "::error file=app.js,line=10,col=15::Something went wrong"
      #     exit 1
